let usersData = [
    {
        id: 'first',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Жизни заголовок вершину первую сбить имеет',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'second',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Продолжил выйти подпоясал оксмокс страна переписали осталось языком ручеек имени всемогущая ее',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'symo.com',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'third',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Собрал реторический журчит пояс lorem? Что предложения маленькая которой решила подпоясал знаках всеми пор',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'microsoft',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    }, {
        id: 'fourth',
        username: 'Michelle Stewart',
        position: 'UX/UI Designer',
        task: 'Mobile app',
        messageDate: 'Monday, 7:32 AM',
        userMessage: 'Города запятых обеспечивает текст? Маленький все залетают оксмокс курсивных',
        avatarClass: 'quatro',
        title: 'New logo for JCD.pl',
        description: '5 days dalays',
        site: 'google.com',
        projectPrice: '22000$',
        projectDeadline: '22 August 2018',
        timeSpent: '0 hours',
        percent: '0'
    },{
        id: 'fifth',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Города от всех текстов мир, за она рыбного. Ручеек до рекламных своего, свое даль то реторический',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'sixth',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Взобравшись, свое. Сбить дал своих, снова от всех, алфавит журчит. Не вершину, его коварный свою.',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'symo.com',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'seventh',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'google.com',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    },{
        id: 'sdgtn',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'ergaw',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'microsoft',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'tmjyh',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'google.com',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    }, {
        id: 'fgngn55',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Жизни заголовок вершину первую сбить имеет',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: '54454',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Продолжил выйти подпоясал оксмокс страна переписали осталось языком ручеек имени всемогущая ее',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'symo.com',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: '5446',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Собрал реторический журчит пояс lorem? Что предложения маленькая которой решила подпоясал знаках всеми пор',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'microsoft',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    }, {
        id: 'ergyjt78k',
        username: 'Michelle Stewart',
        position: 'UX/UI Designer',
        task: 'Mobile app',
        messageDate: 'Monday, 7:32 AM',
        userMessage: 'Города запятых обеспечивает текст? Маленький все залетают оксмокс курсивных',
        avatarClass: 'quatro',
        title: 'New logo for JCD.pl',
        description: '5 days dalays',
        site: 'google.com',
        projectPrice: '22000$',
        projectDeadline: '22 August 2018',
        timeSpent: '0 hours',
        percent: '0'
    },{
        id: 'ergerhyuk',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Города от всех текстов мир, за она рыбного. Ручеек до рекламных своего, свое даль то реторический',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'rdjk6uk',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Взобравшись, свое. Сбить дал своих, снова от всех, алфавит журчит. Не вершину, его коварный свою.',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'symo.com',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'wefgehtyj',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'google.com',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    },{
        id: 'efewgwgw',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'pooowd',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'microsoft',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'pplpp',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'google.com',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    },{
        id: 'dfbtmuym',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Жизни заголовок вершину первую сбить имеет',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'ololol',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Продолжил выйти подпоясал оксмокс страна переписали осталось языком ручеек имени всемогущая ее',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'symo.com',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'rtyr',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Собрал реторический журчит пояс lorem? Что предложения маленькая которой решила подпоясал знаках всеми пор',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'microsoft',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    }, {
        id: 'sdsdsda',
        username: 'Michelle Stewart',
        position: 'UX/UI Designer',
        task: 'Mobile app',
        messageDate: 'Monday, 7:32 AM',
        userMessage: 'Города запятых обеспечивает текст? Маленький все залетают оксмокс курсивных',
        avatarClass: 'quatro',
        title: 'New logo for JCD.pl',
        description: '5 days dalays',
        site: 'google.com',
        projectPrice: '22000$',
        projectDeadline: '22 August 2018',
        timeSpent: '0 hours',
        percent: '0'
    },{
        id: 'pppp',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Города от всех текстов мир, за она рыбного. Ручеек до рекламных своего, свое даль то реторический',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'kkk',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Взобравшись, свое. Сбить дал своих, снова от всех, алфавит журчит. Не вершину, его коварный свою.',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'symo.com',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'ooo',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'google.com',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    },{
        id: 'fff',
        username: 'Michelle Stewart',
        position: 'Account',
        task: 'New website',
        messageDate: 'Today, 5:32 PM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'uno',
        title: 'New websites for Symo.com',
        description: '4 days left',
        site: 'facebook.com',
        projectPrice: '3000$',
        projectDeadline: '3 September 2018',
        timeSpent: '15 hours',
        percent: '100'
    }, {
        id: 'dfs',
        username: 'Jolene Slater',
        position: 'Freelancer',
        task: 'Landing page',
        messageDate: 'Yesterday, 1:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'dos',
        title: 'Free business PSD Template',
        description: '2 days left',
        site: 'microsoft',
        projectPrice: '5110$',
        projectDeadline: '3 June 2018',
        timeSpent: '40 hours',
        percent: '15'
    }, {
        id: 'ggntyn',
        username: 'Lyall Roach',
        position: 'Front End Dev',
        task: 'New dashboard',
        messageDate: 'Sunday, 7:32 AM',
        userMessage: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit ius hic unde at facilis',
        avatarClass: 'tres',
        title: 'Create mego project',
        description: '1 week dalays',
        site: 'google.com',
        projectPrice: '15000$',
        projectDeadline: '15 May 2018',
        timeSpent: '25 hours',
        percent: '62'
    },
];

export default usersData;